# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bigaceproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='time',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
