# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 16:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bigaceproject', '0003_auto_20160205_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rating_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_from', to=settings.AUTH_USER_MODEL)),
                ('rating_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
